### ISSUE TITLE
[Test] 'User' instance fail

### ISSUE THREAD

**Issue by pdtdev** [pdtdev/pw-store-django#2]
Extract from test log:

```
======================================================================
ERROR: test_add_logon_history (passwords.tests.models.LogonHistoryModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/venvs/pw-store-django/passwords/tests/models.py", line 65, in setUp
    create_user()
  File "/usr/local/venvs/pw-store-django/passwords/tests/models.py", line 24, in create_user
    user = User.objects.create_user(username, email, password)
  File "/usr/local/venvs/pw-store-django/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 190, in __get__
    cls._meta.swapped,
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'passwords.User'
```

**Comment by pdtdev** [comment]
Implementation changed the setting AUTH_USER_MODEL to a custom model by sub-classing the AbstractUser 

Test were not updated
